# ===========================================================================
# NEON Mosquito Pulse — ui.R
# v2 flow: the sidebar is gone. The national picker map IS the way to select a
# site; the state/site selectors were relocated onto the landing (a .select-panel
# beside the map, SAME input ids). A slim .top-bar holds theme + temperature +
# How-it-works. The loaded view's hero band carries a "Change site" control and a
# "Report" download. The Santa Rita demo CTAs were removed — users pick a real
# site on the map or the Browse-all list.
# ===========================================================================
ui <- bslib::page_fillable(
  theme = app_theme, title = NULL,
  window_title = "NEON Mosquito Pulse", fillable = FALSE,
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("mosquito.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),

  # ---- persistent top bar (theme + temperature + help) -------------------
  # The two settings that must stay reachable everywhere live here. Site
  # selection moved to the picker map + the landing select-panel below.
  div(class = "top-bar",
    div(class = "top-bar-brand",
      tags$span(class = "tb-mark", "\U0001F99F"),
      tags$span(class = "tb-title", "Mosquito Pulse")),
    div(class = "top-bar-actions",
      actionButton("help", tagList(bs_icon("question-circle"), " How it works"),
                   class = "btn-outline-dark btn-sm tb-help"),
      div(class = "tb-toggle",
        tags$span(class = "tb-toggle-lab", bs_icon("thermometer-half")),
        radioButtons("tempUnit", NULL, choices = c("°F" = "F", "°C" = "C"), selected = "F", inline = TRUE)),
      div(class = "tb-theme",
        tags$span(class = "tb-theme-lab", bs_icon("circle-half")),
        input_dark_mode(id = "colorMode", mode = "light")))
  ),

  div(id = "loadOverlay", class = "load-overlay", div(class = "load-card",
    div(class = "load-spin mascot-spin", MASCOT_CRITTER), div(class = "load-title", "Loading site data"),
    div(id = "loadSite", class = "load-site"), div(class = "load-bar"),
    div(class = "load-note", "Building the swarm board, the monsoon pulse, and the maps."))),
  if (isTRUE(NO_DATA)) div(class = "synth-banner", bs_icon("exclamation-octagon-fill"),
    tags$span(HTML("<b>No data bundled yet.</b> Run <code>Rscript scripts/build_synth_bundle.R</code> (preview) or the real NEON fetch to populate <code>data/</code>. The map below shows the network greyed out until then.")))
  else if (isTRUE(ANY_SYNTHETIC)) div(class = "synth-banner", bs_icon("exclamation-triangle-fill"),
    tags$span(HTML("<b>Preview build.</b> Numbers are representative <b>synthetic</b> mosquito catches, pending the real NEON DP1.10043.001 fetch. They show how the app reads; they are not measurements."))),
  uiOutput("heroStats"),

  # "Open a species profile" picker — was in the sidebar, now a hidden body block
  # revealed on site load (server: shinyjs::show("spPickerWrap")). Same ids
  # (spSel, surpriseBtn) so the server logic is untouched.
  hidden(div(id = "spPickerWrap", class = "indiv-picker-wrap",
    div(class = "ipw-row",
      div(class = "ipw-sel",
        selectizeInput("spSel", label = tagList(bs_icon("search"), " Open a species profile"), choices = NULL,
                       width = "100%", options = list(placeholder = "Pick a species…"))),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"),
                   class = "btn-outline-dark ipw-surprise")))),

  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start!"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash splash-map",
    div(class = "app-hero app-hero-splash",
      h1(class = "app-title", "NEON Mosquito Pulse", span(class = "title-tag", "unofficial")),
      p(class = "app-subtitle", "When the rains come, the mosquitoes follow. Every mosquito NEON catches in its CO2 traps, how busy and how widespread, which genera, the female-skewed catch, and how the seasonal pulse rides the summer monsoon across a continent of climates. Built on CO2-trap collections (DP1.10043.001).")),
    p(tags$b("Tap a site on the map"), " (sized by mosquito richness, coloured by biome) to explore it, or pick one by name in the panel below the map. ", tags$b("46 sites"), " from desert washes to arctic tundra."),
    div(class = "picker-map-wrap", leafletOutput("nationalPicker", height = "440px")),

    # ---- relocated select panel (was the sidebar) ----------------------
    # Same input ids the server's selection + load path depend on (stateSel,
    # site, loadBtn). Tapping a dot is the primary path; this panel is the
    # by-name fallback. No date window — bundles load whole for this app.
    div(class = "select-panel",
      div(class = "sp-head", bs_icon("sliders"), " Or pick a site by name"),
      div(class = "sp-row",
        div(class = "sp-field",
          selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " State"), choices = NULL, width = "100%")),
        div(class = "sp-field",
          selectInput("site", label = tagList(bs_icon("pin-map-fill"), " Site"), choices = NULL, width = "100%"))),
      uiOutput("siteBio"),
      actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                   class = "btn-primary btn-lg load-btn sp-load", onclick = "smtLoadStart()")),

    tags$details(class = "site-browse",
      tags$summary(class = "site-browse-summary",
        tags$span(class = "sbs-label", bs_icon("list-ul"), " Browse all 46 sites as a list"),
        tags$span(class = "sbs-chevron", bs_icon("chevron-down"))),
      div(class = "site-browse-body", uiOutput("siteCards"))))),
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    div(class = "hero-caveat", bs_icon("activity"),
      tags$span(HTML("Counts are an <b>activity index</b> (mosquitoes per trap-night), not a population. CO2 traps lure host-seeking <b>females</b>, so a big night means high activity, not a high headcount."))),
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goPulse", tagList(bs_icon("activity"), div("The Pulse"), tags$small("the monsoon curve")), class = "home-btn home-btn-star"),
          actionButton("goBoard", tagList(bs_icon("bug-fill"), div("Swarm Board"), tags$small("every species, pinnable")), class = "home-btn"),
          actionButton("goClimate", tagList(bs_icon("globe-americas"), div("Across the continent"), tags$small("46 sites by climate")), class = "home-btn"),
          actionButton("goSpecies", tagList(bs_icon("droplet-fill"), div("Taxon Profile"), tags$small("one species up close")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("traps across the site")), class = "home-btn")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "Most-active species",
            info_pop("Activity index",
              p("Each species' ", tags$b("activity index"), ", mosquitoes per trap-night, coloured by ", tags$b("genus"), " (", tags$span(style="color:#e8920f;font-weight:700","Culex"), " / ", tags$span(style="color:#7c52e0;font-weight:700","Aedes"), " / ", tags$span(style="color:#3fb6c9;font-weight:700","Anopheles"), " / others)."),
              p(class="pop-caveat", bs_icon("exclamation-triangle"), " This is a ", tags$b("within-site activity index, not a population"), ". A single big-catch night can lift a species; the share of trap-nights it shows up on (the Swarm Board's other axis) is the steadier read."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("topBar", height = "440px"))),
        card(card_head("stars", "The story so far", info_pop("Story", p("Written from this site's live data."))),
          uiOutput("siteInsights")),
        card(full_screen = TRUE,
          card_head("pie-chart", "Who's in the trap: genus and sex",
            info_pop("Composition",
              p("Top bar: the ", tags$b("genus"), " shares of the catch. Bottom bar: the ", tags$b("sex"), " split."),
              p(class="pop-caveat", bs_icon("exclamation-triangle"), " CO2 traps catch mostly host-seeking ", tags$b("females"), " by design, so a nearly-all-female bar is the trap working, not a population sex ratio."))),
          uiOutput("compInsight"),
          spin(plotlyOutput("compStrip", height = "200px")),
          div(class = "vector-note", bs_icon("shield-exclamation"),
            tags$span(HTML("<b>Culex</b> includes the main West Nile virus carrier in the western US. This app shows where and when they are active. It is a heads-up, not an infection or risk measure, which NEON tracks with a separate program."))))),
      nav_panel(title = tagList(bs_icon("activity"), " The Pulse"), value = "pulse",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The monsoon pulse"),
          p("Mosquito activity by week of the year, averaged across years, with the site's summer-rain window shaded behind it. In the desert the pulse rides the monsoon."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only"))),
        card(full_screen = TRUE,
          card_head("activity", "Activity index by week, against the rains",
            info_pop("Reading the pulse",
              p("The line is the ", tags$b("median activity index"), " (mosquitoes per trap-night) by week of the year across all sampled years (the median, not the mean, because mosquito catch is wildly skewed and one fluke year shouldn't define the peak); the band is the ", tags$b("middle 50% of years"), " (the inter-quartile spread). The ", tags$span(style="color:#5f9e12;font-weight:700","green shading"), ", where shown, is the site's summer-rain / monsoon window from its precipitation climatology (drawn only at sites with a real NEON gauge and a summer rain peak)."),
              p("Weeks with no trapping are gaps, not zeros. The pulse following the rains is the pattern this app is built to show, ", tags$b("correlational"), ", within this one site. Rainfall is shown only where a NEON gauge exists."))),
          div(class = "sizelab-toolbar",
            downloadButton("pulseCsv", "Download the pulse (CSV)", class = "smt-clear-btn")),
          uiOutput("pulseInsight"),
          spin(plotlyOutput("pulsePlot", height = "400px"))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species accumulation (by trap-night)",
              info_pop("Accumulation", p("As more collection occasions (each trap-night is one) accumulate, how many species turn up. A flattening curve means most catchable species have been found."))),
            uiOutput("accumInsight"), spin(plotlyOutput("accumPlot", height = "320px"))),
          card(full_screen = TRUE,
            card_head("calculator", "How many species really? (Chao2)",
              info_pop("Chao2", p(tags$b("Chao2"), " is an incidence-based, bias-corrected ", tags$b("minimum"), " estimate of richness. CO2 traps miss day-active and rare species, so the true total is higher than what is caught."))),
            uiOutput("chaoBanner")))),
      nav_panel(title = tagList(bs_icon("bug-fill"), " Swarm Board"), value = "board",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Every species on one board",
             info_pop("Swarm Board",
               p("Each dot is a ", tags$b("species"), ", placed by ", tags$b("ubiquity"), " (% of trap-nights it shows up on, a steadier axis than the index) and its ", tags$b("activity index"), " (mosquitoes per trap-night)."),
               p(tags$b("Tap a dot"), " to pin its card; open any species' full profile. Faint dots are caught on too few nights to place reliably."))),
          p("Each dot is a species, how widespread × how busy. Culex (West Nile group) is flagged. Tap to pin a card."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only"))),
        card(full_screen = TRUE,
          card_head("bug-fill", "Ubiquity × activity index, by species",
            info_pop("Reading this", p("Top-right = everywhere and busy; top-left = locally busy specialist; bottom-right = thinly everywhere. The ", tags$span(style="color:#9a5f08;font-weight:700","gold diamond"), " is the species you're viewing. Colour = genus."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "boardPin", spin(plotlyOutput("swarmBoard", height = "540px")))),
        uiOutput("spCardSlot")),
      nav_panel(title = tagList(bs_icon("globe-americas"), " Across the continent"), value = "climate",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("One protocol, 46 sites, a continent of climates"),
          p("Each dot is a NEON site, placed by its warm-season climate against its mosquito community. Deserts read against monsoon rain, cooler sites against degree-days. Tap a dot to pin its card or jump to that site."),
          span(class = "scope-chip scope-all", bs_icon("globe-americas"), " All 46 NEON sites, not just this one")),
          div(class = "sizelab-controls",
            selectInput("gradMetric", tagList(bs_icon("bar-chart"), " Community metric (y)"),
              choices = c("Activity index · per trap-night" = "index", "Richness · effort-rarefied" = "rarefied",
                          "Richness · observed (raw)" = "observed", "Culex share (% of catch)" = "culex",
                          "Common-species diversity (Hill q1)" = "hill1"), selected = "rarefied", width = "240px"),
            radioButtons("gradX", "Climate axis (x)", inline = TRUE,
              choices = c("Warm-season temperature" = "temp", "Warm-season precip · gauge sites" = "precip"), selected = "temp"))),
        card(full_screen = TRUE,
          card_head("globe-americas", "Mosquito community across the climate gradient",
            info_pop("Reading this",
              p("Warmer, wetter sites tend to hold a richer, busier mosquito community. Each dot is a site; ", tags$b("size = survey effort"), " (trap-nights); colour = biome; the ", tags$span(style="color:#9a5f08;font-weight:700","gold diamond"), " is the site you're viewing. The activity-index view uses a ", tags$b("log scale"), " because one site can run thousands of times busier than another."),
              p("This is ", tags$b("space-for-time"), ", 46 different places observed at once, not one place warming or wetting, so it's correlational, confounded by biome and latitude. Activity is a within-site index, so compare sites by ", tags$b("direction, not by who has the higher raw number"), ". Precipitation shows only the sites with a NEON gauge."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveClimate()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            downloadButton("crossSiteCsv", "Cross-site table (CSV)", class = "smt-clear-btn"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a site to pin its card")),
          div(class = "smt-pinnable", id = "climatePin", spin(plotlyOutput("climateGradient", height = "560px"))))),
      nav_panel(title = tagList(bs_icon("search"), " Search the network"), value = "search",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Search the whole network"),
          p("Look across every bundled NEON site at once. Find a mosquito species and see where it has been caught, or pull the sites that pass a threshold you set. Everything runs on the bundled data, so it is instant, and you can jump straight to any site."),
          span(class = "scope-chip scope-all", bs_icon("globe-americas"), " All 46 NEON sites, not just this one"))),
        radioButtons("searchMode", NULL, inline = TRUE,
          choices = c("Find a species" = "taxon", "Find sites by threshold" = "threshold"), selected = "taxon"),
        conditionalPanel("input.searchMode == 'taxon'",
          card(card_head("droplet-fill", "Find a mosquito species",
              info_pop("Reading this",
                p("Pick any mosquito species in the network. The table lists every bundled site where it has been caught, with that site's ", tags$b("activity index"), " for the species (whole-trap-scaled catch per trap-night, a ", tags$b("within-site index, not an absolute ranking"), ") and its ubiquity (the share of attempted trap-nights it showed up on)."),
                p(tags$b("Culex"), " species are flagged, they are the main West Nile virus vector group."))),
            selectizeInput("searchTaxon", "Species", choices = NULL,
              options = list(placeholder = "Start typing a species name…", maxOptions = 200), width = "100%"),
            div(class = "search-caption", uiOutput("searchTaxonCaption")),
            div(style = "width:100%;", DTOutput("searchTaxonTbl")))),
        conditionalPanel("input.searchMode == 'threshold'",
          card(card_head("sliders", "Find sites by threshold",
              info_pop("Reading this",
                p("Set a cutoff and the table returns the sites that pass it. ", tags$b("Culex share"), " is the percent of a site's whole-trap catch that is Culex (the West Nile vector group). The ", tags$b("activity index"), " is the site's mosquitoes per trap-night."),
                p("Both are ", tags$b("within-site indices, not absolute rankings"), ", so read them as direction, not as a leaderboard."))),
            div(class = "sizelab-controls",
              selectInput("threshMetric", tagList(bs_icon("funnel"), " Filter sites by"), width = "260px",
                choices = c("Culex (West Nile group) share %" = "culex", "Activity index · per trap-night" = "index")),
              numericInput("threshVal", "is greater than", value = 5, min = 0, step = 1, width = "160px")),
            div(class = "search-caption", uiOutput("searchThreshCaption")),
            div(style = "width:100%;", DTOutput("searchThreshTbl"))))),
      nav_panel(title = tagList(bs_icon("droplet-fill"), " Taxon Profile"), value = "species", uiOutput("speciesProfile")),
      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Mosquito traps across the site"),
          p("Each marker is a NEON CO2-trap grid, sized by richness and coloured by your chosen metric. ", tags$b("Tap a grid"), " for the full list of mosquitoes caught there."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "200px", choices = c("Species richness" = "richness", "Activity per trap-night" = "per_tn")),
            selectInput("view", "Basemap", width = "160px", choices = c("Terrain" = "Esri.WorldTopoMap", "Light" = "CartoDB.Positron", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "560px")),
        uiOutput("gridPanel")),
      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Mosquito%20Pulse",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Mosquito%20Pulse", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Data: NEON Mosquitoes sampled from CO2 traps (DP1.10043.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
