# ===========================================================================
# NEON Mosquito Pulse — ui.R
# ===========================================================================
ui <- bslib::page_sidebar(
  theme = app_theme, title = NULL,
  window_title = "NEON Mosquito Pulse", fillable = FALSE,
  tags$head(
    tags$link(rel = "preconnect", href = "https://fonts.googleapis.com"),
    tags$link(rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = NA),
    tags$link(rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700;800&display=swap"),
    tags$link(rel = "stylesheet", href = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.min.css"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/sweetalert2@11.10.0/dist/sweetalert2.all.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/canvas-confetti@1.9.2/dist/confetti.browser.min.js"),
    tags$script(src = "https://cdn.jsdelivr.net/npm/html-to-image@1.11.13/dist/html-to-image.js"),
    tags$link(rel = "stylesheet", href = asset_url("styles.css")),
    tags$link(rel = "stylesheet", href = asset_url("mosquito.css")),
    tags$script(src = asset_url("app.js")),
    tags$script(src = asset_url("pincards.js"))
  ),
  useShinyjs(),
  sidebar = sidebar(
    width = 320, class = "control-deck",
    div(class = "brand", div(class = "brand-mark", "\U0001F99F"),
      div(div(class = "brand-title", "Mosquito Pulse"), div(class = "brand-sub", "NEON field observatory"))),
    selectInput("stateSel", label = tagList(bs_icon("geo-alt-fill"), " 1 · Pick a state"), choices = NULL, width = "100%"),
    selectInput("site", label = tagList(bs_icon("pin-map-fill"), " 2 · Pick a site"), choices = NULL, width = "100%"),
    uiOutput("siteBio"),
    actionButton("loadBtn", tagList(bs_icon("globe-americas"), " Explore this site"),
                 class = "btn-primary btn-lg w-100 load-btn", onclick = "smtLoadStart()"),
    actionButton("demoBtn", tagList(bs_icon("stars"), " or open the Santa Rita demo"),
                 class = "btn-link btn-sm w-100 reset-demo", onclick = "smtLoadStart('Santa Rita · demo dataset')"),
    hidden(div(id = "spPickerWrap", hr(class = "deck-hr"),
      selectizeInput("spSel", label = tagList(bs_icon("search"), " Open a species profile"), choices = NULL,
                     options = list(placeholder = "Pick a species…")),
      actionButton("surpriseBtn", tagList(bs_icon("dice-5-fill"), " Surprise me"), class = "btn-outline-dark btn-sm w-100"))),
    hr(class = "deck-hr"),
    actionButton("help", tagList(bs_icon("question-circle"), " How it works"), class = "btn-outline-dark btn-sm w-100"),
    div(class = "theme-toggle-row", tags$span(class = "theme-toggle-lab", bs_icon("circle-half"), " Theme"),
      input_dark_mode(id = "colorMode", mode = "light")),
    div(class = "theme-toggle-row temp-toggle-row", tags$span(class = "theme-toggle-lab", bs_icon("thermometer-half"), " Temperature"),
      radioButtons("tempUnit", NULL, choices = c("°F" = "F", "°C" = "C"), selected = "F", inline = TRUE)),
    div(class = "deck-foot", bs_icon("database"), " NEON ", tags$code("DP1.10043.001"),
      br(), tags$a(href = "https://desertdatalabs.com", target = "_blank", bs_icon("box-arrow-up-right"), " Desert Data Labs"))
  ),
  div(id = "loadOverlay", class = "load-overlay", div(class = "load-card",
    div(class = "load-spin mascot-spin", MASCOT_CRITTER), div(class = "load-title", "Loading site data"),
    div(id = "loadSite", class = "load-site"), div(class = "load-bar"),
    div(class = "load-note", "Building the swarm board, the monsoon pulse, and the maps."))),
  if (isTRUE(NO_DATA)) div(class = "synth-banner", bs_icon("exclamation-octagon-fill"),
    tags$span(HTML("<b>No data bundled yet.</b> Run <code>Rscript scripts/build_synth_bundle.R</code> (preview) or the real NEON fetch to populate <code>data/</code>. The map below shows the network greyed out until then.")))
  else if (isTRUE(ANY_SYNTHETIC)) div(class = "synth-banner", bs_icon("exclamation-triangle-fill"),
    tags$span(HTML("<b>Preview build.</b> Numbers are representative <b>synthetic</b> mosquito catches, pending the real NEON DP1.10043.001 fetch. They show how the app reads; they are not measurements."))),
  uiOutput("heroStats"),
  div(id = "splash",
    div(class = "splash-guide",
      div(class = "sg-bubble", "Pick a site to start!"),
      div(class = "sg-mascot", MASCOT_CRITTER)),
    div(class = "splash splash-map",
    div(class = "app-hero app-hero-splash",
      h1(class = "app-title", "NEON Mosquito Pulse", span(class = "title-tag", "unofficial")),
      p(class = "app-subtitle", "When the rains come, the mosquitoes follow. Every mosquito NEON catches in its CO2 traps, how busy and how widespread, which genera, the female-skewed catch, and how the seasonal pulse rides the summer monsoon across a continent of climates. Built on CO2-trap collections (DP1.10043.001).")),
    p(tags$b("Tap a site on the map"), " (sized by mosquito richness, coloured by biome), search the sidebar, or open the Santa Rita demo, Sonoran-desert monsoon country south of Tucson. ", tags$b("46 sites"), " from desert washes to arctic tundra."),
    div(class = "picker-map-wrap", leafletOutput("nationalPicker", height = "440px")),
    tags$details(class = "site-browse",
      tags$summary(class = "site-browse-summary",
        tags$span(class = "sbs-label", bs_icon("list-ul"), " Browse all 46 sites as a list"),
        tags$span(class = "sbs-chevron", bs_icon("chevron-down"))),
      div(class = "site-browse-body", uiOutput("siteCards"))),
    div(class = "picker-actions", actionButton("demoBtn2", tagList(bs_icon("stars"), " Open the Santa Rita demo"),
      class = "btn-primary btn-lg", onclick = "smtLoadStart('Santa Rita · demo dataset')")))),
  div(id = "mainTabsWrap", class = "main-tabs-wrap",
    div(class = "hero-caveat", bs_icon("activity"),
      tags$span(HTML("Counts are an <b>activity index</b> (mosquitoes per trap-night), not a population. CO2 traps lure host-seeking <b>females</b>, so a big night means high activity, not a high headcount."))),
    navset_card_tab(id = "tabs",
      nav_panel(title = tagList(bs_icon("compass"), " Overview"), value = "overview",
        div(class = "home-nav",
          actionButton("goPulse", tagList(bs_icon("activity"), div("The Pulse"), tags$small("the monsoon curve")), class = "home-btn home-btn-star"),
          actionButton("goBoard", tagList(bs_icon("bug-fill"), div("Swarm Board"), tags$small("every species, pinnable")), class = "home-btn"),
          actionButton("goClimate", tagList(bs_icon("globe-americas"), div("Across the continent"), tags$small("46 sites by climate")), class = "home-btn"),
          actionButton("goSpecies", tagList(bs_icon("droplet-fill"), div("Taxon Profile"), tags$small("one species up close")), class = "home-btn"),
          actionButton("goMap", tagList(bs_icon("map-fill"), div("Map"), tags$small("traps across the site")), class = "home-btn")),
        card(full_screen = TRUE,
          card_head("bar-chart-steps", "Most-active species",
            info_pop("Activity index",
              p("Each species' ", tags$b("activity index"), ", mosquitoes per trap-night, coloured by ", tags$b("genus"), " (", tags$span(style="color:#e8920f;font-weight:700","Culex"), " / ", tags$span(style="color:#7c52e0;font-weight:700","Aedes"), " / ", tags$span(style="color:#3fb6c9;font-weight:700","Anopheles"), " / others)."),
              p(class="pop-caveat", bs_icon("exclamation-triangle"), " This is a ", tags$b("within-site activity index, not a population"), ". A single big-catch night can lift a species; the share of trap-nights it shows up on (the Swarm Board's other axis) is the steadier read."))),
          uiOutput("overviewInsight"),
          spin(plotlyOutput("topBar", height = "440px"))),
        card(card_head("stars", "The story so far", info_pop("Story", p("Written from this site's live data."))),
          uiOutput("siteInsights")),
        card(full_screen = TRUE,
          card_head("pie-chart", "Who's in the trap: genus and sex",
            info_pop("Composition",
              p("Top bar: the ", tags$b("genus"), " shares of the catch. Bottom bar: the ", tags$b("sex"), " split."),
              p(class="pop-caveat", bs_icon("exclamation-triangle"), " CO2 traps catch mostly host-seeking ", tags$b("females"), " by design, so a nearly-all-female bar is the trap working, not a population sex ratio."))),
          uiOutput("compInsight"),
          spin(plotlyOutput("compStrip", height = "200px")),
          div(class = "vector-note", bs_icon("shield-exclamation"),
            tags$span(HTML("<b>Culex</b> includes the main West Nile virus carrier in the western US. This app shows where and when they are active. It is a heads-up, not an infection or risk measure, which NEON tracks with a separate program."))))),
      nav_panel(title = tagList(bs_icon("activity"), " The Pulse"), value = "pulse",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("The monsoon pulse"),
          p("Mosquito activity by week of the year, averaged across years, with the site's summer-rain window shaded behind it. In the desert the pulse rides the monsoon."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only"))),
        card(full_screen = TRUE,
          card_head("activity", "Activity index by week, against the rains",
            info_pop("Reading the pulse",
              p("The line is the ", tags$b("median activity index"), " (mosquitoes per trap-night) by week of the year across all sampled years (the median, not the mean, because mosquito catch is wildly skewed and one fluke year shouldn't define the peak); the band is the ", tags$b("middle 50% of years"), " (the inter-quartile spread). The ", tags$span(style="color:#5f9e12;font-weight:700","green shading"), ", where shown, is the site's summer-rain / monsoon window from its precipitation climatology (drawn only at sites with a real NEON gauge and a summer rain peak)."),
              p("Weeks with no trapping are gaps, not zeros. The pulse following the rains is the pattern this app is built to show, ", tags$b("correlational"), ", within this one site. Rainfall is shown only where a NEON gauge exists."))),
          uiOutput("pulseInsight"),
          spin(plotlyOutput("pulsePlot", height = "400px"))),
        layout_columns(col_widths = c(7, 5),
          card(full_screen = TRUE,
            card_head("graph-up", "Species accumulation (by trap-night)",
              info_pop("Accumulation", p("As more collection occasions (each trap-night is one) accumulate, how many species turn up. A flattening curve means most catchable species have been found."))),
            uiOutput("accumInsight"), spin(plotlyOutput("accumPlot", height = "320px"))),
          card(full_screen = TRUE,
            card_head("calculator", "How many species really? (Chao2)",
              info_pop("Chao2", p(tags$b("Chao2"), " is an incidence-based, bias-corrected ", tags$b("minimum"), " estimate of richness. CO2 traps miss day-active and rare species, so the true total is higher than what is caught."))),
            uiOutput("chaoBanner")))),
      nav_panel(title = tagList(bs_icon("bug-fill"), " Swarm Board"), value = "board",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Every species on one board",
             info_pop("Swarm Board",
               p("Each dot is a ", tags$b("species"), ", placed by ", tags$b("ubiquity"), " (% of trap-nights it shows up on, a steadier axis than the index) and its ", tags$b("activity index"), " (mosquitoes per trap-night)."),
               p(tags$b("Tap a dot"), " to pin its card; open any species' full profile. Faint dots are caught on too few nights to place reliably."))),
          p("Each dot is a species, how widespread × how busy. Culex (West Nile group) is flagged. Tap to pin a card."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only"))),
        card(full_screen = TRUE,
          card_head("bug-fill", "Ubiquity × activity index, by species",
            info_pop("Reading this", p("Top-right = everywhere and busy; top-left = locally busy specialist; bottom-right = thinly everywhere. The ", tags$span(style="color:#9a5f08;font-weight:700","gold diamond"), " is the species you're viewing. Colour = genus."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveScatter()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a dot to pin its card")),
          div(class = "smt-pinnable", id = "boardPin", spin(plotlyOutput("swarmBoard", height = "540px")))),
        uiOutput("spCardSlot")),
      nav_panel(title = tagList(bs_icon("globe-americas"), " Across the continent"), value = "climate",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("One protocol, 46 sites, a continent of climates"),
          p("Each dot is a NEON site, placed by its warm-season climate against its mosquito community. Deserts read against monsoon rain, cooler sites against degree-days. Tap a dot to pin its card or jump to that site."),
          span(class = "scope-chip scope-all", bs_icon("globe-americas"), " All 46 NEON sites, not just this one")),
          div(class = "sizelab-controls",
            selectInput("gradMetric", tagList(bs_icon("bar-chart"), " Community metric (y)"),
              choices = c("Activity index · per trap-night" = "index", "Richness · effort-rarefied" = "rarefied",
                          "Richness · observed (raw)" = "observed", "Culex share (% of catch)" = "culex",
                          "Common-species diversity (Hill q1)" = "hill1"), selected = "index", width = "240px"),
            radioButtons("gradX", "Climate axis (x)", inline = TRUE,
              choices = c("Warm-season temperature" = "temp", "Warm-season precip · gauge sites" = "precip"), selected = "temp"))),
        card(full_screen = TRUE,
          card_head("globe-americas", "Mosquito community across the climate gradient",
            info_pop("Reading this",
              p("Warmer, wetter sites tend to run a bigger seasonal mosquito pulse. Each dot is a site; ", tags$b("size = survey effort"), " (trap-nights); colour = biome; the ", tags$span(style="color:#9a5f08;font-weight:700","gold diamond"), " is the site you're viewing."),
              p("This is ", tags$b("space-for-time"), ", 46 different places observed at once, not one place warming or wetting, so it's correlational, confounded by biome and latitude. Activity is a within-site index, so compare sites by ", tags$b("direction, not by who has the higher raw number"), ". Precipitation shows only the sites with a NEON gauge."))),
          div(class = "sizelab-toolbar",
            tags$button(class = "smt-snap-btn", type = "button", onclick = "smtSaveClimate()", bsicons::bs_icon("camera-fill"), " Download (with pinned cards)"),
            downloadButton("crossSiteCsv", "Cross-site table (CSV)", class = "smt-clear-btn"),
            tags$button(class = "smt-clear-btn", type = "button", onclick = "smtClearPins()", bsicons::bs_icon("eraser-fill"), " Clear pins"),
            tags$span(class = "sizelab-hint", bs_icon("hand-index-thumb"), " interactive · tap a site to pin its card")),
          div(class = "smt-pinnable", id = "climatePin", spin(plotlyOutput("climateGradient", height = "560px"))))),
      nav_panel(title = tagList(bs_icon("droplet-fill"), " Taxon Profile"), value = "species", uiOutput("speciesProfile")),
      nav_panel(title = tagList(bs_icon("map-fill"), " Map"), value = "map",
        div(class = "tab-head", div(class = "tab-head-text",
          h4("Mosquito traps across the site"),
          p("Each marker is a NEON CO2-trap grid, sized by richness and coloured by your chosen metric. ", tags$b("Tap a grid"), " for the full list of mosquitoes caught there."),
          span(class = "scope-chip scope-site", bs_icon("geo-alt-fill"), " Showing this site only")),
          div(class = "map-controls",
            selectInput("mapMetric", "Colour by", width = "200px", choices = c("Species richness" = "richness", "Activity per trap-night" = "per_tn")),
            selectInput("view", "Basemap", width = "160px", choices = c("Terrain" = "Esri.WorldTopoMap", "Light" = "CartoDB.Positron", "Satellite" = "Esri.WorldImagery")))),
        spin(leafletOutput("map", height = "560px")),
        uiOutput("gridPanel")),
      nav_panel(title = tagList(bs_icon("info-circle"), " About"), value = "about", uiOutput("aboutPanel"))
    )),
  div(class = "ddl-footer",
    div(tags$a(class = "custom-cta", href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Mosquito%20Pulse",
      span(class = "hand", "\U0001F44B"), "Questions or feedback? Get in touch with Desert Data Labs.")),
    p(style = "margin-top:12px", HTML("Built by <strong>Desert Data Labs</strong> · Tucson, AZ · get in touch →"),
      tags$a(href = "mailto:desertdatalabs@gmail.com?subject=NEON%20Mosquito%20Pulse", "desertdatalabs@gmail.com")),
    p(style = "font-size:12px;opacity:.85", "Data: NEON Mosquitoes sampled from CO2 traps (DP1.10043.001). Not affiliated with NEON, Battelle, or the NSF. An educational data-exploration tool."))
)
